'use client'

import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { AiModelHint } from '@/components/ai/AiModelHint'
import { AiFlowLoader } from '@/components/ai/AiFlowLoader'

const COVER_STAGES = [
  { id: 'context', label: 'Reading your resume & job' },
  { id: 'draft', label: 'Drafting your cover letter' },
  { id: 'polish', label: 'Polishing tone & flow' },
] as const

interface CoverLetterPanelProps {
  jobId?: string | null
  tailoredResumeId?: string | null
  initialLetter?: string
  embedded?: boolean
  autoGenerate?: boolean
  onAutoGenerateDone?: () => void
}

export function CoverLetterPanel({
  jobId,
  tailoredResumeId,
  initialLetter = '',
  embedded = false,
  autoGenerate = false,
  onAutoGenerateDone,
}: CoverLetterPanelProps) {
  const [letter, setLetter] = useState(initialLetter)
  const [loading, setLoading] = useState(false)
  const [loadingStage, setLoadingStage] = useState(0)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const startedRef = useRef(false)
  const inFlightRef = useRef(false)

  async function getTargetTailoredResume() {
    if (!jobId) return
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) throw new Error('Not signed in')
    const { data: tr } = tailoredResumeId
      ? await supabase
          .from('tailored_resumes')
          .select('id, cover_letter')
          .eq('user_id', user.id)
          .eq('id', tailoredResumeId)
          .maybeSingle()
      : await supabase
          .from('tailored_resumes')
          .select('id, cover_letter')
          .eq('user_id', user.id)
          .eq('job_id', jobId)
          .order('version', { ascending: false })
          .limit(1)
          .maybeSingle()
    if (!tr?.id) {
      throw new Error('Create a tailored resume first so the cover letter has a resume context.')
    }
    return { supabase, tr }
  }

  async function generate(opts?: { skipIfExists?: boolean }) {
    if (inFlightRef.current) return
    inFlightRef.current = true
    setLoading(true)
    setLoadingStage(0)
    setError(null)
    const tick = window.setInterval(() => {
      setLoadingStage(i => Math.min(i + 1, COVER_STAGES.length - 1))
    }, 2800)
    try {
      const target = await getTargetTailoredResume()
      if (!target) return
      if (target.tr.cover_letter) {
        setLetter(target.tr.cover_letter)
        if (opts?.skipIfExists) return
      }
      const res = await fetch('/api/tailor/cover-letter', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ tailoredResumeId: target.tr.id }),
      })
      if (!res.ok) {
        const body = (await res.json().catch(() => ({}))) as { error?: string }
        throw new Error(body.error || 'Generation failed')
      }
      const text = await res.text()
      setLetter(text)
    } catch (err) {
      setError(
        (err instanceof Error ? err.message : 'Failed') +
          ' We stopped — we will not retry automatically.',
      )
    } finally {
      window.clearInterval(tick)
      setLoading(false)
      inFlightRef.current = false
      onAutoGenerateDone?.()
    }
  }

  useEffect(() => {
    if (autoGenerate && jobId && !initialLetter.trim()) {
      if (startedRef.current) return
      startedRef.current = true
      void generate({ skipIfExists: true })
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- one-shot from chooser
  }, [autoGenerate, jobId])

  async function save() {
    setSaving(true)
    setError(null)
    try {
      const target = await getTargetTailoredResume()
      if (!target) return
      const { error: updateError } = await target.supabase
        .from('tailored_resumes')
        .update({ cover_letter: letter })
        .eq('id', target.tr.id)
      if (updateError) throw updateError
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Save failed')
    } finally {
      setSaving(false)
    }
  }

  if (loading) {
    return (
      <AiFlowLoader
        title="Writing your cover letter"
        subtitle="Grounded in your resume and this job's requirements."
        stages={[...COVER_STAGES]}
        activeIndex={loadingStage}
        className="min-h-[280px]"
      />
    )
  }

  return (
    <div className="space-y-4">
      {embedded ? null : (
      <div>
        <h2 className="text-lg font-semibold">Cover Letter</h2>
        <p className="text-sm text-muted-foreground mt-1">
          Generate or review the cover letter for this job.
        </p>
      </div>
      )}
      {!jobId ? (
        <p className="text-sm text-muted-foreground">
          Select a job in the{' '}
          <Link href="/dashboard/tracker" className="underline">
            Applications
          </Link>{' '}
          tracker, then open Documents to match.
        </p>
      ) : (
        <>
          <div className="flex flex-wrap gap-2 items-center">
            <Button type="button" size="sm" onClick={() => void generate()} disabled={loading || saving}>
              Generate with AI
            </Button>
            <Button type="button" size="sm" variant="outline" onClick={() => void save()} disabled={loading || saving}>
              {saving ? 'Saving…' : 'Save edits'}
            </Button>
            <AiModelHint uses="strong" />
          </div>
          {error && <p className="text-sm text-destructive">{error}</p>}
          <Textarea
            value={letter}
            onChange={e => setLetter(e.target.value)}
            rows={16}
            placeholder="Write your cover letter here, or tap Generate with AI…"
          />
        </>
      )}
    </div>
  )
}
